// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCODKv9Qro6V5GjeBXjqZLxhUEAIKEIGKA',
    appId: '1:266830134123:web:07644ac89161ef8bddea2e',
    messagingSenderId: '266830134123',
    projectId: 'cascadia-growth-insights',
    authDomain: 'cascadia-growth-insights.firebaseapp.com',
    storageBucket: 'cascadia-growth-insights.appspot.com',
    measurementId: 'G-GL7H8WEL1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEew6oAE-fDmPlowNxQ8sIkUlnq2mK8HA',
    appId: '1:266830134123:android:23fe26dddd3907dfddea2e',
    messagingSenderId: '266830134123',
    projectId: 'cascadia-growth-insights',
    storageBucket: 'cascadia-growth-insights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Vcts2ioeYo_uL7-Dek6dIlU8fRwq8dE',
    appId: '1:266830134123:ios:fcf42e6241fbbaf8ddea2e',
    messagingSenderId: '266830134123',
    projectId: 'cascadia-growth-insights',
    storageBucket: 'cascadia-growth-insights.appspot.com',
    iosBundleId: 'com.example.cgiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Vcts2ioeYo_uL7-Dek6dIlU8fRwq8dE',
    appId: '1:266830134123:ios:9402acc3710f07d1ddea2e',
    messagingSenderId: '266830134123',
    projectId: 'cascadia-growth-insights',
    storageBucket: 'cascadia-growth-insights.appspot.com',
    iosBundleId: 'com.example.cgiApp.RunnerTests',
  );
}
